services:
  - type: web
    name: educate-web
    env: php
    buildCommand: "./bin/render-build.sh"
    startCommand: "heroku-php-apache2 public/"
    envVars:
      - key: APP_NAME
        value: EducaTe
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: educate-db
          property: connectionString
      - key: DB_CONNECTION
        value: pgsql
      - key: SESSION_SECURE_COOKIE
        value: true
      - key: SESSION_DRIVER
        value: database

databases:
  - name: educate-db
    databaseName: educate
    user: educate
